apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "event-microservice"
  KAFKA_GROUP_ID: "activity-consumer-group"
  KAFKA_TOPIC: "user-activities"
  MONGODB_URI: "mongodb+srv://Estate_hub:m2y8FxWRLWHa7PLF@cluster0.b24gnxs.mongodb.net/activities"