apiVersion: v1
kind: Service
metadata:
  name: event-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: event-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

